// Code generated by MockGen. DO NOT EDIT.
// Source: rq.go

// Package cascadeadaptormocks is a generated GoMock package.
package cascadeadaptormocks

import (
	context "context"
	reflect "reflect"

	codec "github.com/LumeraProtocol/supernode/v2/pkg/codec"
	adaptors "github.com/LumeraProtocol/supernode/v2/supernode/services/cascade/adaptors"
	gomock "github.com/golang/mock/gomock"
)

// MockCodecService is a mock of CodecService interface.
type MockCodecService struct {
	ctrl     *gomock.Controller
	recorder *MockCodecServiceMockRecorder
}

// MockCodecServiceMockRecorder is the mock recorder for MockCodecService.
type MockCodecServiceMockRecorder struct {
	mock *MockCodecService
}

// NewMockCodecService creates a new mock instance.
func NewMockCodecService(ctrl *gomock.Controller) *MockCodecService {
	mock := &MockCodecService{ctrl: ctrl}
	mock.recorder = &MockCodecServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodecService) EXPECT() *MockCodecServiceMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockCodecService) Decode(ctx context.Context, req adaptors.DecodeRequest) (adaptors.DecodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", ctx, req)
	ret0, _ := ret[0].(adaptors.DecodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockCodecServiceMockRecorder) Decode(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockCodecService)(nil).Decode), ctx, req)
}

// EncodeInput mocks base method.
func (m *MockCodecService) EncodeInput(ctx context.Context, taskID, path string, dataSize int) (adaptors.EncodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeInput", ctx, taskID, path, dataSize)
	ret0, _ := ret[0].(adaptors.EncodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncodeInput indicates an expected call of EncodeInput.
func (mr *MockCodecServiceMockRecorder) EncodeInput(ctx, taskID, path, dataSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeInput", reflect.TypeOf((*MockCodecService)(nil).EncodeInput), ctx, taskID, path, dataSize)
}

// PrepareDecode mocks base method.
func (m *MockCodecService) PrepareDecode(ctx context.Context, actionID string, layout codec.Layout) ([]string, func(int, string, []byte) (string, error), func() error, *codec.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareDecode", ctx, actionID, layout)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(func(int, string, []byte) (string, error))
	ret2, _ := ret[2].(func() error)
	ret3, _ := ret[3].(*codec.Workspace)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// PrepareDecode indicates an expected call of PrepareDecode.
func (mr *MockCodecServiceMockRecorder) PrepareDecode(ctx, actionID, layout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareDecode", reflect.TypeOf((*MockCodecService)(nil).PrepareDecode), ctx, actionID, layout)
}
