// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mocks/client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	lumera "github.com/LumeraProtocol/supernode/sdk/adapters/lumera"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAction mocks base method.
func (m *MockClient) GetAction(ctx context.Context, actionID string) (lumera.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAction", ctx, actionID)
	ret0, _ := ret[0].(lumera.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAction indicates an expected call of GetAction.
func (mr *MockClientMockRecorder) GetAction(ctx, actionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAction", reflect.TypeOf((*MockClient)(nil).GetAction), ctx, actionID)
}

// GetSupernodes mocks base method.
func (m *MockClient) GetSupernodes(ctx context.Context, height int64) ([]lumera.Supernode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupernodes", ctx, height)
	ret0, _ := ret[0].([]lumera.Supernode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupernodes indicates an expected call of GetSupernodes.
func (mr *MockClientMockRecorder) GetSupernodes(ctx, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupernodes", reflect.TypeOf((*MockClient)(nil).GetSupernodes), ctx, height)
}
