// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	alts "github.com/LumeraProtocol/supernode/common/net/credentials/alts"

	mock "github.com/stretchr/testify/mock"

	node "github.com/LumeraProtocol/supernode/walletnode/node"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

// Connect provides a mock function with given fields: ctx, address, secInfo, taskID
func (_m *ClientInterface) Connect(ctx context.Context, address string, secInfo *alts.SecInfo, taskID string) (node.ConnectionInterface, error) {
	ret := _m.Called(ctx, address, secInfo, taskID)

	var r0 node.ConnectionInterface
	if rf, ok := ret.Get(0).(func(context.Context, string, *alts.SecInfo, string) node.ConnectionInterface); ok {
		r0 = rf(ctx, address, secInfo, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.ConnectionInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *alts.SecInfo, string) error); ok {
		r1 = rf(ctx, address, secInfo, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClientInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientInterface(t mockConstructorTestingTNewClientInterface) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
