// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	node "github.com/LumeraProtocol/supernode/walletnode/node"
	mock "github.com/stretchr/testify/mock"
)

// ConnectionInterface is an autogenerated mock type for the ConnectionInterface type
type ConnectionInterface struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ConnectionInterface) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Done provides a mock function with given fields:
func (_m *ConnectionInterface) Done() <-chan struct{} {
	ret := _m.Called()

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// DownloadNft provides a mock function with given fields:
func (_m *ConnectionInterface) DownloadNft() node.DownloadNftInterface {
	ret := _m.Called()

	var r0 node.DownloadNftInterface
	if rf, ok := ret.Get(0).(func() node.DownloadNftInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.DownloadNftInterface)
		}
	}

	return r0
}

// RegisterCascade provides a mock function with given fields:
func (_m *ConnectionInterface) RegisterCascade() node.RegisterCascadeInterface {
	ret := _m.Called()

	var r0 node.RegisterCascadeInterface
	if rf, ok := ret.Get(0).(func() node.RegisterCascadeInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.RegisterCascadeInterface)
		}
	}

	return r0
}

// RegisterCollection provides a mock function with given fields:
func (_m *ConnectionInterface) RegisterCollection() node.RegisterCollectionInterface {
	ret := _m.Called()

	var r0 node.RegisterCollectionInterface
	if rf, ok := ret.Get(0).(func() node.RegisterCollectionInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.RegisterCollectionInterface)
		}
	}

	return r0
}

// RegisterNft provides a mock function with given fields:
func (_m *ConnectionInterface) RegisterNft() node.RegisterNftInterface {
	ret := _m.Called()

	var r0 node.RegisterNftInterface
	if rf, ok := ret.Get(0).(func() node.RegisterNftInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.RegisterNftInterface)
		}
	}

	return r0
}

// RegisterSense provides a mock function with given fields:
func (_m *ConnectionInterface) RegisterSense() node.RegisterSenseInterface {
	ret := _m.Called()

	var r0 node.RegisterSenseInterface
	if rf, ok := ret.Get(0).(func() node.RegisterSenseInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.RegisterSenseInterface)
		}
	}

	return r0
}

type mockConstructorTestingTNewConnectionInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnectionInterface creates a new instance of ConnectionInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnectionInterface(t mockConstructorTestingTNewConnectionInterface) *ConnectionInterface {
	mock := &ConnectionInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
