// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	files "github.com/LumeraProtocol/supernode/common/storage/files"
	mock "github.com/stretchr/testify/mock"

	raptorqnode "github.com/LumeraProtocol/supernode/raptorq/node"

	types "github.com/LumeraProtocol/supernode/common/types"

	walletnode "github.com/LumeraProtocol/supernode/proto/walletnode"
)

// RegisterCascadeInterface is an autogenerated mock type for the RegisterCascadeInterface type
type RegisterCascadeInterface struct {
	mock.Mock
}

// AcceptedNodes provides a mock function with given fields: ctx
func (_m *RegisterCascadeInterface) AcceptedNodes(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectTo provides a mock function with given fields: ctx, primaryNode
func (_m *RegisterCascadeInterface) ConnectTo(ctx context.Context, primaryNode types.MeshedSuperNode) error {
	ret := _m.Called(ctx, primaryNode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MeshedSuperNode) error); ok {
		r0 = rf(ctx, primaryNode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDDServerStats provides a mock function with given fields: ctx
func (_m *RegisterCascadeInterface) GetDDServerStats(ctx context.Context) (*walletnode.DDServerStatsReply, error) {
	ret := _m.Called(ctx)

	var r0 *walletnode.DDServerStatsReply
	if rf, ok := ret.Get(0).(func(context.Context) *walletnode.DDServerStatsReply); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*walletnode.DDServerStatsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDupeDetectionDBHash provides a mock function with given fields: ctx
func (_m *RegisterCascadeInterface) GetDupeDetectionDBHash(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopMNs provides a mock function with given fields: ctx, block
func (_m *RegisterCascadeInterface) GetTopMNs(ctx context.Context, block int) (*walletnode.GetTopMNsReply, error) {
	ret := _m.Called(ctx, block)

	var r0 *walletnode.GetTopMNsReply
	if rf, ok := ret.Get(0).(func(context.Context, int) *walletnode.GetTopMNsReply); ok {
		r0 = rf(ctx, block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*walletnode.GetTopMNsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MeshNodes provides a mock function with given fields: ctx, meshedNodes
func (_m *RegisterCascadeInterface) MeshNodes(ctx context.Context, meshedNodes []types.MeshedSuperNode) error {
	ret := _m.Called(ctx, meshedNodes)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.MeshedSuperNode) error); ok {
		r0 = rf(ctx, meshedNodes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendActionAct provides a mock function with given fields: ctx, actionRegTxid
func (_m *RegisterCascadeInterface) SendActionAct(ctx context.Context, actionRegTxid string) error {
	ret := _m.Called(ctx, actionRegTxid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, actionRegTxid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendRegMetadata provides a mock function with given fields: ctx, regMetadata
func (_m *RegisterCascadeInterface) SendRegMetadata(ctx context.Context, regMetadata *types.ActionRegMetadata) error {
	ret := _m.Called(ctx, regMetadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.ActionRegMetadata) error); ok {
		r0 = rf(ctx, regMetadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendSignedTicket provides a mock function with given fields: ctx, ticket, signature, rqIdsFile, encoderParams
func (_m *RegisterCascadeInterface) SendSignedTicket(ctx context.Context, ticket []byte, signature []byte, rqIdsFile []byte, encoderParams raptorqnode.EncoderParameters) (string, error) {
	ret := _m.Called(ctx, ticket, signature, rqIdsFile, encoderParams)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, []byte, raptorqnode.EncoderParameters) string); ok {
		r0 = rf(ctx, ticket, signature, rqIdsFile, encoderParams)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte, []byte, []byte, raptorqnode.EncoderParameters) error); ok {
		r1 = rf(ctx, ticket, signature, rqIdsFile, encoderParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessID provides a mock function with given fields:
func (_m *RegisterCascadeInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, IsPrimary
func (_m *RegisterCascadeInterface) Session(ctx context.Context, IsPrimary bool) error {
	ret := _m.Called(ctx, IsPrimary)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, IsPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadAsset provides a mock function with given fields: ctx, asset
func (_m *RegisterCascadeInterface) UploadAsset(ctx context.Context, asset *files.File) error {
	ret := _m.Called(ctx, asset)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *files.File) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRegisterCascadeInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegisterCascadeInterface creates a new instance of RegisterCascadeInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegisterCascadeInterface(t mockConstructorTestingTNewRegisterCascadeInterface) *RegisterCascadeInterface {
	mock := &RegisterCascadeInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
