// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/LumeraProtocol/supernode/common/types"

	walletnode "github.com/LumeraProtocol/supernode/proto/walletnode"
)

// RegisterCollectionInterface is an autogenerated mock type for the RegisterCollectionInterface type
type RegisterCollectionInterface struct {
	mock.Mock
}

// AcceptedNodes provides a mock function with given fields: ctx
func (_m *RegisterCollectionInterface) AcceptedNodes(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectTo provides a mock function with given fields: ctx, primaryNode
func (_m *RegisterCollectionInterface) ConnectTo(ctx context.Context, primaryNode types.MeshedSuperNode) error {
	ret := _m.Called(ctx, primaryNode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MeshedSuperNode) error); ok {
		r0 = rf(ctx, primaryNode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDDServerStats provides a mock function with given fields: ctx
func (_m *RegisterCollectionInterface) GetDDServerStats(ctx context.Context) (*walletnode.DDServerStatsReply, error) {
	ret := _m.Called(ctx)

	var r0 *walletnode.DDServerStatsReply
	if rf, ok := ret.Get(0).(func(context.Context) *walletnode.DDServerStatsReply); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*walletnode.DDServerStatsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDupeDetectionDBHash provides a mock function with given fields: ctx
func (_m *RegisterCollectionInterface) GetDupeDetectionDBHash(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopMNs provides a mock function with given fields: ctx, block
func (_m *RegisterCollectionInterface) GetTopMNs(ctx context.Context, block int) (*walletnode.GetTopMNsReply, error) {
	ret := _m.Called(ctx, block)

	var r0 *walletnode.GetTopMNsReply
	if rf, ok := ret.Get(0).(func(context.Context, int) *walletnode.GetTopMNsReply); ok {
		r0 = rf(ctx, block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*walletnode.GetTopMNsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MeshNodes provides a mock function with given fields: ctx, meshedNodes
func (_m *RegisterCollectionInterface) MeshNodes(ctx context.Context, meshedNodes []types.MeshedSuperNode) error {
	ret := _m.Called(ctx, meshedNodes)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.MeshedSuperNode) error); ok {
		r0 = rf(ctx, meshedNodes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendTicketForSignature provides a mock function with given fields: ctx, ticket, signature, burnTxID
func (_m *RegisterCollectionInterface) SendTicketForSignature(ctx context.Context, ticket []byte, signature []byte, burnTxID string) (string, error) {
	ret := _m.Called(ctx, ticket, signature, burnTxID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, string) string); ok {
		r0 = rf(ctx, ticket, signature, burnTxID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte, []byte, string) error); ok {
		r1 = rf(ctx, ticket, signature, burnTxID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessID provides a mock function with given fields:
func (_m *RegisterCollectionInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, IsPrimary
func (_m *RegisterCollectionInterface) Session(ctx context.Context, IsPrimary bool) error {
	ret := _m.Called(ctx, IsPrimary)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, IsPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRegisterCollectionInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegisterCollectionInterface creates a new instance of RegisterCollectionInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegisterCollectionInterface(t mockConstructorTestingTNewRegisterCollectionInterface) *RegisterCollectionInterface {
	mock := &RegisterCollectionInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
