// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	files "github.com/LumeraProtocol/supernode/common/storage/files"
	mock "github.com/stretchr/testify/mock"

	types "github.com/LumeraProtocol/supernode/common/types"

	walletnode "github.com/LumeraProtocol/supernode/proto/walletnode"
)

// RegisterSenseInterface is an autogenerated mock type for the RegisterSenseInterface type
type RegisterSenseInterface struct {
	mock.Mock
}

// AcceptedNodes provides a mock function with given fields: ctx
func (_m *RegisterSenseInterface) AcceptedNodes(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectTo provides a mock function with given fields: ctx, primaryNode
func (_m *RegisterSenseInterface) ConnectTo(ctx context.Context, primaryNode types.MeshedSuperNode) error {
	ret := _m.Called(ctx, primaryNode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.MeshedSuperNode) error); ok {
		r0 = rf(ctx, primaryNode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDDServerStats provides a mock function with given fields: ctx
func (_m *RegisterSenseInterface) GetDDServerStats(ctx context.Context) (*walletnode.DDServerStatsReply, error) {
	ret := _m.Called(ctx)

	var r0 *walletnode.DDServerStatsReply
	if rf, ok := ret.Get(0).(func(context.Context) *walletnode.DDServerStatsReply); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*walletnode.DDServerStatsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDupeDetectionDBHash provides a mock function with given fields: ctx
func (_m *RegisterSenseInterface) GetDupeDetectionDBHash(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopMNs provides a mock function with given fields: ctx, block
func (_m *RegisterSenseInterface) GetTopMNs(ctx context.Context, block int) (*walletnode.GetTopMNsReply, error) {
	ret := _m.Called(ctx, block)

	var r0 *walletnode.GetTopMNsReply
	if rf, ok := ret.Get(0).(func(context.Context, int) *walletnode.GetTopMNsReply); ok {
		r0 = rf(ctx, block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*walletnode.GetTopMNsReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MeshNodes provides a mock function with given fields: ctx, meshedNodes
func (_m *RegisterSenseInterface) MeshNodes(ctx context.Context, meshedNodes []types.MeshedSuperNode) error {
	ret := _m.Called(ctx, meshedNodes)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.MeshedSuperNode) error); ok {
		r0 = rf(ctx, meshedNodes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProbeImage provides a mock function with given fields: ctx, image
func (_m *RegisterSenseInterface) ProbeImage(ctx context.Context, image *files.File) ([]byte, bool, string, bool, error) {
	ret := _m.Called(ctx, image)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, *files.File) []byte); ok {
		r0 = rf(ctx, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(context.Context, *files.File) bool); ok {
		r1 = rf(ctx, image)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 string
	if rf, ok := ret.Get(2).(func(context.Context, *files.File) string); ok {
		r2 = rf(ctx, image)
	} else {
		r2 = ret.Get(2).(string)
	}

	var r3 bool
	if rf, ok := ret.Get(3).(func(context.Context, *files.File) bool); ok {
		r3 = rf(ctx, image)
	} else {
		r3 = ret.Get(3).(bool)
	}

	var r4 error
	if rf, ok := ret.Get(4).(func(context.Context, *files.File) error); ok {
		r4 = rf(ctx, image)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// SendActionAct provides a mock function with given fields: ctx, actionRegTxid
func (_m *RegisterSenseInterface) SendActionAct(ctx context.Context, actionRegTxid string) error {
	ret := _m.Called(ctx, actionRegTxid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, actionRegTxid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendRegMetadata provides a mock function with given fields: ctx, regMetadata
func (_m *RegisterSenseInterface) SendRegMetadata(ctx context.Context, regMetadata *types.ActionRegMetadata) error {
	ret := _m.Called(ctx, regMetadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.ActionRegMetadata) error); ok {
		r0 = rf(ctx, regMetadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendSignedTicket provides a mock function with given fields: ctx, ticket, signature, ddFpFile
func (_m *RegisterSenseInterface) SendSignedTicket(ctx context.Context, ticket []byte, signature []byte, ddFpFile []byte) (string, error) {
	ret := _m.Called(ctx, ticket, signature, ddFpFile)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, []byte) string); ok {
		r0 = rf(ctx, ticket, signature, ddFpFile)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte, []byte, []byte) error); ok {
		r1 = rf(ctx, ticket, signature, ddFpFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessID provides a mock function with given fields:
func (_m *RegisterSenseInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, IsPrimary
func (_m *RegisterSenseInterface) Session(ctx context.Context, IsPrimary bool) error {
	ret := _m.Called(ctx, IsPrimary)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, IsPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRegisterSenseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegisterSenseInterface creates a new instance of RegisterSenseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegisterSenseInterface(t mockConstructorTestingTNewRegisterSenseInterface) *RegisterSenseInterface {
	mock := &RegisterSenseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
