// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	supernode "github.com/LumeraProtocol/supernode/proto/supernode"

	types "github.com/LumeraProtocol/supernode/common/types"
)

// HealthCheckChallengeInterface is an autogenerated mock type for the HealthCheckChallengeInterface type
type HealthCheckChallengeInterface struct {
	mock.Mock
}

// BroadcastHealthCheckChallengeMetrics provides a mock function with given fields: ctx, req
func (_m *HealthCheckChallengeInterface) BroadcastHealthCheckChallengeMetrics(ctx context.Context, req types.ProcessBroadcastHealthCheckChallengeMetricsRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ProcessBroadcastHealthCheckChallengeMetricsRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BroadcastHealthCheckChallengeResult provides a mock function with given fields: ctx, req
func (_m *HealthCheckChallengeInterface) BroadcastHealthCheckChallengeResult(ctx context.Context, req *supernode.BroadcastHealthCheckChallengeRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.BroadcastHealthCheckChallengeRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessHealthCheckChallenge provides a mock function with given fields: ctx, challengeMessage
func (_m *HealthCheckChallengeInterface) ProcessHealthCheckChallenge(ctx context.Context, challengeMessage *supernode.HealthCheckChallengeMessage) error {
	ret := _m.Called(ctx, challengeMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.HealthCheckChallengeMessage) error); ok {
		r0 = rf(ctx, challengeMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessID provides a mock function with given fields:
func (_m *HealthCheckChallengeInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, nodeID, sessID
func (_m *HealthCheckChallengeInterface) Session(ctx context.Context, nodeID string, sessID string) error {
	ret := _m.Called(ctx, nodeID, sessID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeID, sessID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyHealthCheckChallenge provides a mock function with given fields: ctx, challengeMessage
func (_m *HealthCheckChallengeInterface) VerifyHealthCheckChallenge(ctx context.Context, challengeMessage *supernode.HealthCheckChallengeMessage) error {
	ret := _m.Called(ctx, challengeMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.HealthCheckChallengeMessage) error); ok {
		r0 = rf(ctx, challengeMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyHealthCheckEvaluationResult provides a mock function with given fields: ctx, challengeMessage
func (_m *HealthCheckChallengeInterface) VerifyHealthCheckEvaluationResult(ctx context.Context, challengeMessage *supernode.HealthCheckChallengeMessage) (types.HealthCheckMessage, error) {
	ret := _m.Called(ctx, challengeMessage)

	var r0 types.HealthCheckMessage
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.HealthCheckChallengeMessage) types.HealthCheckMessage); ok {
		r0 = rf(ctx, challengeMessage)
	} else {
		r0 = ret.Get(0).(types.HealthCheckMessage)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *supernode.HealthCheckChallengeMessage) error); ok {
		r1 = rf(ctx, challengeMessage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHealthCheckChallengeInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewHealthCheckChallengeInterface creates a new instance of HealthCheckChallengeInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHealthCheckChallengeInterface(t mockConstructorTestingTNewHealthCheckChallengeInterface) *HealthCheckChallengeInterface {
	mock := &HealthCheckChallengeInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
