// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RegisterCascadeInterface is an autogenerated mock type for the RegisterCascadeInterface type
type RegisterCascadeInterface struct {
	mock.Mock
}

// SendCascadeTicketSignature provides a mock function with given fields: ctx, nodeID, signature
func (_m *RegisterCascadeInterface) SendCascadeTicketSignature(ctx context.Context, nodeID string, signature []byte) error {
	ret := _m.Called(ctx, nodeID, signature)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, nodeID, signature)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessID provides a mock function with given fields:
func (_m *RegisterCascadeInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, nodeID, sessID
func (_m *RegisterCascadeInterface) Session(ctx context.Context, nodeID string, sessID string) error {
	ret := _m.Called(ctx, nodeID, sessID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeID, sessID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRegisterCascadeInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegisterCascadeInterface creates a new instance of RegisterCascadeInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegisterCascadeInterface(t mockConstructorTestingTNewRegisterCascadeInterface) *RegisterCascadeInterface {
	mock := &RegisterCascadeInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
