// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RegisterCollectionInterface is an autogenerated mock type for the RegisterCollectionInterface type
type RegisterCollectionInterface struct {
	mock.Mock
}

// SendCollectionTicketSignature provides a mock function with given fields: ctx, nodeID, signature
func (_m *RegisterCollectionInterface) SendCollectionTicketSignature(ctx context.Context, nodeID string, signature []byte) error {
	ret := _m.Called(ctx, nodeID, signature)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, nodeID, signature)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessID provides a mock function with given fields:
func (_m *RegisterCollectionInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, nodeID, sessID
func (_m *RegisterCollectionInterface) Session(ctx context.Context, nodeID string, sessID string) error {
	ret := _m.Called(ctx, nodeID, sessID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeID, sessID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRegisterCollectionInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegisterCollectionInterface creates a new instance of RegisterCollectionInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegisterCollectionInterface(t mockConstructorTestingTNewRegisterCollectionInterface) *RegisterCollectionInterface {
	mock := &RegisterCollectionInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
