// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	supernode "github.com/LumeraProtocol/supernode/proto/supernode"

	types "github.com/LumeraProtocol/supernode/common/types"
)

// StorageChallengeInterface is an autogenerated mock type for the StorageChallengeInterface type
type StorageChallengeInterface struct {
	mock.Mock
}

// BroadcastStorageChallengeMetrics provides a mock function with given fields: ctx, req
func (_m *StorageChallengeInterface) BroadcastStorageChallengeMetrics(ctx context.Context, req types.ProcessBroadcastChallengeMetricsRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ProcessBroadcastChallengeMetricsRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BroadcastStorageChallengeResult provides a mock function with given fields: ctx, req
func (_m *StorageChallengeInterface) BroadcastStorageChallengeResult(ctx context.Context, req *supernode.BroadcastStorageChallengeRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.BroadcastStorageChallengeRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessStorageChallenge provides a mock function with given fields: ctx, challengeMessage
func (_m *StorageChallengeInterface) ProcessStorageChallenge(ctx context.Context, challengeMessage *supernode.StorageChallengeMessage) error {
	ret := _m.Called(ctx, challengeMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.StorageChallengeMessage) error); ok {
		r0 = rf(ctx, challengeMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessID provides a mock function with given fields:
func (_m *StorageChallengeInterface) SessID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Session provides a mock function with given fields: ctx, nodeID, sessID
func (_m *StorageChallengeInterface) Session(ctx context.Context, nodeID string, sessID string) error {
	ret := _m.Called(ctx, nodeID, sessID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, nodeID, sessID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyEvaluationResult provides a mock function with given fields: ctx, challengeMessage
func (_m *StorageChallengeInterface) VerifyEvaluationResult(ctx context.Context, challengeMessage *supernode.StorageChallengeMessage) (types.Message, error) {
	ret := _m.Called(ctx, challengeMessage)

	var r0 types.Message
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.StorageChallengeMessage) types.Message); ok {
		r0 = rf(ctx, challengeMessage)
	} else {
		r0 = ret.Get(0).(types.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *supernode.StorageChallengeMessage) error); ok {
		r1 = rf(ctx, challengeMessage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyStorageChallenge provides a mock function with given fields: ctx, challengeMessage
func (_m *StorageChallengeInterface) VerifyStorageChallenge(ctx context.Context, challengeMessage *supernode.StorageChallengeMessage) error {
	ret := _m.Called(ctx, challengeMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernode.StorageChallengeMessage) error); ok {
		r0 = rf(ctx, challengeMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStorageChallengeInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageChallengeInterface creates a new instance of StorageChallengeInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageChallengeInterface(t mockConstructorTestingTNewStorageChallengeInterface) *StorageChallengeInterface {
	mock := &StorageChallengeInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
