package storagechallenge

import (
	"container/list"
	"crypto/sha256"
	"sync"
)

// indexSizeCache memoises INDEX-class artifact byte lengths derived from
// cascadekit.GenerateIndexFiles, keyed by (signatures, rqIdsIc, rqIdsMax).
//
// LEP-6 review (Matee, 2026-05-06) — M4: ResolveArtifactSize for INDEX class
// previously re-ran cascadekit.GenerateIndexFiles on every dispatch (and on
// every recheck), regenerating the entire index file set just to read one
// ordinal's byte length. Two consequences: (a) hot-path CPU/RAM burn on the
// dispatcher; (b) the regenerated bytes are full files we never use. The
// cache stores only the per-ordinal byte length (uint64), bounded to 256
// tickets via LRU eviction. The cache key is a SHA-256 digest over the
// concatenated (signatures, rqIdsIc, rqIdsMax) inputs to GenerateIndexFiles
// so two tickets with identical inputs collapse to one entry; collisions
// are not possible because the digest depends on every input GenerateIndexFiles
// reads.
type indexSizeCache struct {
	mu       sync.Mutex
	cap      int
	order    *list.List
	items    map[[32]byte]*list.Element
}

type indexSizeEntry struct {
	key   [32]byte
	sizes []uint64
}

const indexSizeCacheCap = 256

var globalIndexSizeCache = newIndexSizeCache(indexSizeCacheCap)

func newIndexSizeCache(capacity int) *indexSizeCache {
	if capacity <= 0 {
		capacity = 1
	}
	return &indexSizeCache{
		cap:   capacity,
		order: list.New(),
		items: make(map[[32]byte]*list.Element, capacity),
	}
}

func indexSizeKey(signatures string, rqIdsIc uint32, rqIdsMax uint32) [32]byte {
	h := sha256.New()
	_, _ = h.Write([]byte(signatures))
	_, _ = h.Write([]byte{0})
	var buf [8]byte
	buf[0] = byte(rqIdsIc >> 24)
	buf[1] = byte(rqIdsIc >> 16)
	buf[2] = byte(rqIdsIc >> 8)
	buf[3] = byte(rqIdsIc)
	buf[4] = byte(rqIdsMax >> 24)
	buf[5] = byte(rqIdsMax >> 16)
	buf[6] = byte(rqIdsMax >> 8)
	buf[7] = byte(rqIdsMax)
	_, _ = h.Write(buf[:])
	var out [32]byte
	copy(out[:], h.Sum(nil))
	return out
}

// get returns a per-ordinal size slice if cached, or nil if not. Updates LRU.
func (c *indexSizeCache) get(key [32]byte) []uint64 {
	c.mu.Lock()
	defer c.mu.Unlock()
	if el, ok := c.items[key]; ok {
		c.order.MoveToFront(el)
		return el.Value.(*indexSizeEntry).sizes
	}
	return nil
}

// put inserts sizes under key, evicting the LRU entry if full.
func (c *indexSizeCache) put(key [32]byte, sizes []uint64) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if el, ok := c.items[key]; ok {
		el.Value.(*indexSizeEntry).sizes = sizes
		c.order.MoveToFront(el)
		return
	}
	if c.order.Len() >= c.cap {
		oldest := c.order.Back()
		if oldest != nil {
			delete(c.items, oldest.Value.(*indexSizeEntry).key)
			c.order.Remove(oldest)
		}
	}
	el := c.order.PushFront(&indexSizeEntry{key: key, sizes: sizes})
	c.items[key] = el
}

// length returns the current cache occupancy. Test-only helper.
func (c *indexSizeCache) length() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.order.Len()
}
