package raptorq

import (
	"bytes"
	"context"
	"encoding/json"
	"io/fs"
	"math/rand/v2"
	"os"
	"path/filepath"
	"strconv"

	"github.com/LumeraProtocol/supernode/pkg/errors"
	"github.com/LumeraProtocol/supernode/pkg/logtrace"
	"github.com/LumeraProtocol/supernode/pkg/utils"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/cosmos/btcutil/base58"
	"github.com/cosmos/cosmos-sdk/types"
	"github.com/google/uuid"
)

const (
	InputEncodeFileName      = "input.data"
	SeparatorByte       byte = 46 // separator in dd_and_fingerprints.signature i.e. '.'
)

// Config contains path to where symbolid files are generated by raptorq service
type Config struct {
	RqFilesDir string
}

// RawSymbolIDFile represents raw content of symbolid files generated by raptorq service
type RawSymbolIDFile struct {
	ID                string   `json:"id"`
	BlockHash         string   `json:"block_hash"`
	PastelID          string   `json:"pastel_id"`
	SymbolIdentifiers []string `json:"symbol_identifiers"`
}

// EncoderParameters represents the encoding params used by raptorq service
type EncoderParameters struct {
	Oti []byte
}

// EncodeInfo represents the response returns by encodeInfo method
type EncodeInfo struct {
	SymbolIDFiles map[string]RawSymbolIDFile
	EncoderParam  EncoderParameters
}

func (s *Client) GenRQIdentifiersFiles(ctx context.Context, fields logtrace.Fields, data []byte, operationBlockHash string, pastelID string, rqMax uint32) (RQIDsIc uint32, RQIDs []string, RQIDsFile []byte, RQEncodeParams EncoderParameters, err error) {
	encodeInfo, err := s.encodeInfo(ctx, fields, data, rqMax, operationBlockHash, pastelID)
	if err != nil {
		return RQIDsIc, RQIDs, RQIDsFile, RQEncodeParams, status.Errorf(codes.Internal, "generate RaptorQ symbols identifiers")
	}

	var rqIDsFilesCount uint32
	for i := range encodeInfo.SymbolIDFiles {
		if len(encodeInfo.SymbolIDFiles[i].SymbolIdentifiers) == 0 {
			return RQIDsIc, RQIDs, RQIDsFile, RQEncodeParams, status.Errorf(codes.Internal, "empty symbol identifiers - rawFile")
		}

		RQIDsIc, RQIDs, RQIDsFile, err := s.generateRQIDs(ctx, encodeInfo.SymbolIDFiles[i], pastelID, rqMax)
		if err != nil {
			return RQIDsIc, RQIDs, RQIDsFile, RQEncodeParams, status.Errorf(codes.Internal, "create RQIDs file")
		}
		rqIDsFilesCount++
		break
	}
	if rqIDsFilesCount != rqMax {
		return RQIDsIc, RQIDs, RQIDsFile, RQEncodeParams, status.Errorf(codes.Internal, "number of RaptorQ symbol identifiers files must be %d, most probably old version of rq-service is installed", rqMax)
	}

	RQEncodeParams = encodeInfo.EncoderParam

	return RQIDsIc, RQIDs, RQIDsFile, RQEncodeParams, nil
}

func (s *Client) encodeInfo(ctx context.Context, fields logtrace.Fields, data []byte, copies uint32, blockHash string, pastelID string) (*EncodeInfo, error) {
	s.semaphore <- struct{}{} // Acquire slot
	defer func() {
		<-s.semaphore // Release the semaphore slot
	}()

	if data == nil {
		return nil, errors.Errorf("invalid data")
	}

	_, inputPath, err := createInputEncodeFile(s.config.RqFilesDir, data)
	if err != nil {
		return nil, errors.Errorf("create input file: %w", err)
	}
	res, err := s.EncodeMetaData(ctx, EncodeMetadataRequest{
		FilesNumber: copies,
		BlockHash:   blockHash,
		PastelId:    pastelID,
		Path:        inputPath,
	})
	if err != nil {
		return nil, errors.Errorf("encode metadata %s: %w", res.Path, err)
	}

	filesMap, err := scanSymbolIDFiles(res.Path)
	if err != nil {
		return nil, errors.Errorf("scan symbol id files folder %s: %w", res.Path, err)
	}

	if len(filesMap) != int(copies) {
		return nil, errors.Errorf("symbol id files count not match: expect %d, output %d", copies, len(filesMap))
	}

	output := &EncodeInfo{
		SymbolIDFiles: filesMap,
		EncoderParam: EncoderParameters{
			Oti: res.EncoderParameters,
		},
	}

	if err := os.Remove(inputPath); err != nil {
		logtrace.Error(ctx, "encode info: error removing input file", fields)
	}

	return output, nil
}

func (s *Client) generateRQIDs(ctx context.Context, rawFile RawSymbolIDFile, callerPastelID string, maxFiles uint32) (RQIDsIc uint32, RQIDs []string, RQIDsFile []byte, err error) {
	rqIDsfile, err := json.Marshal(rawFile)
	if err != nil {
		return RQIDsIc, RQIDs, RQIDsFile, errors.Errorf("marshal rqID file")
	}

	// FIXME : msgs param
	signature, err := s.lumeraClient.Sign(ctx, callerPastelID, []types.Msg{})
	if err != nil {
		return RQIDsIc, RQIDs, RQIDsFile, errors.Errorf("sign identifiers file: %w", err)
	}

	encRqIDsfile := utils.B64Encode(rqIDsfile)

	var buffer bytes.Buffer
	buffer.Write(encRqIDsfile)
	buffer.WriteString(".")
	buffer.Write(signature)
	rqIDFile := buffer.Bytes()

	RQIDsIc = rand.Uint32()
	RQIDs, _, err = getIDFiles(ctx, rqIDFile, RQIDsIc, maxFiles)
	if err != nil {
		return RQIDsIc, RQIDs, RQIDsFile, errors.Errorf("get ID Files: %w", err)
	}

	comp, err := utils.HighCompress(ctx, rqIDFile)
	if err != nil {
		return RQIDsIc, RQIDs, RQIDsFile, errors.Errorf("compress: %w", err)
	}
	RQIDsFile = utils.B64Encode(comp)

	return RQIDsIc, RQIDs, RQIDsFile, nil
}

func createInputEncodeFile(base string, data []byte) (taskPath string, inputFile string, err error) {
	taskPath, err = createTaskFolder(base)

	if err != nil {
		return "", "", errors.Errorf("create task folder: %w", err)
	}

	inputFile = filepath.Join(taskPath, InputEncodeFileName)
	err = writeFile(inputFile, data)

	if err != nil {
		return "", "", errors.Errorf("write file: %w", err)
	}

	return taskPath, inputFile, nil
}

func createTaskFolder(base string, subDirs ...string) (string, error) {
	taskID := randID()
	taskPath := filepath.Join(base, taskID)
	taskPath = filepath.Join(taskPath, filepath.Join(subDirs...))

	err := os.MkdirAll(taskPath, 0750)

	if err != nil {
		return "", err
	}

	return taskPath, nil
}

func randID() string {
	id := uuid.NewString()
	return id[0:8]
}

func writeFile(path string, data []byte) error {
	return os.WriteFile(path, data, 0750)
}

// scan symbol id files in "meta" folder, return map of file Ids & contents of file (as list of line)
func scanSymbolIDFiles(dirPath string) (map[string]RawSymbolIDFile, error) {
	filesMap := make(map[string]RawSymbolIDFile)

	err := filepath.Walk(dirPath, func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return errors.Errorf("scan a path %s: %w", path, err)
		}

		if info.IsDir() {
			// TODO - compare it to root
			return nil
		}

		fileID := filepath.Base(path)

		configFile, err := os.Open(path)
		if err != nil {
			return errors.Errorf("opening file: %s - err: %w", path, err)
		}
		defer configFile.Close()

		file := RawSymbolIDFile{}
		jsonParser := json.NewDecoder(configFile)
		if err = jsonParser.Decode(&file); err != nil {
			return errors.Errorf("parsing file: %s - err: %w", path, err)
		}

		filesMap[fileID] = file

		return nil
	})

	if err != nil {
		return nil, err
	}

	return filesMap, nil
}

// GetIDFiles generates ID Files for dd_and_fingerprints files and rq_id files
// file is b64 encoded file appended with signatures and compressed, ic is the initial counter
// and max is the number of ids to generate
func getIDFiles(ctx context.Context, file []byte, ic uint32, max uint32) (ids []string, files [][]byte, err error) {
	idFiles := make([][]byte, 0, max)
	ids = make([]string, 0, max)
	var buffer bytes.Buffer

	for i := uint32(0); i < max; i++ {
		buffer.Reset()
		counter := ic + i

		buffer.Write(file)
		buffer.WriteByte(SeparatorByte)
		buffer.WriteString(strconv.Itoa(int(counter))) // Using the string representation to maintain backward compatibility

		compressedData, err := utils.HighCompress(ctx, buffer.Bytes()) // Ensure you're using the same compression level
		if err != nil {
			return ids, idFiles, errors.Errorf("compress identifiers file: %w", err)
		}

		idFiles = append(idFiles, compressedData)

		hash, err := utils.Sha3256hash(compressedData)
		if err != nil {
			return ids, idFiles, errors.Errorf("sha3-256-hash error getting an id file: %w", err)
		}

		ids = append(ids, base58.Encode(hash))
	}

	return ids, idFiles, nil
}
