name: Setup Environment
description: Sets up Go and installs system dependencies

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install libwebp-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebp-dev
      shell: bash
      