name: Setup Environment
description: Sets up Go (dynamically from go.mod) and installs system dependencies

inputs:
  bust_lumera_retag:
    description: "One-time: remove lumera v1.8.0 sums after retag"
    required: false
    default: 'false'
outputs:
  go-version:
    description: "Go version parsed from go.mod"
    value: ${{ steps.get-go-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Get Go version from go.mod
      id: get-go-version
      shell: bash
      run: |
        GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+(\.[0-9]+)?$' go.mod | cut -d ' ' -f 2)
        echo "Found Go version: $GO_VERSION"
        echo "version=$GO_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ steps.get-go-version.outputs.version }}
        cache: true

    - name: Install libwebp-dev
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebp-dev make 

    - name: One-time reset retagged lumera checksums
      if: ${{ inputs.bust_lumera_retag == 'true' }}
      shell: bash
      run: |
        echo "Busting go.sum entries for github.com/LumeraProtocol/lumera v1.8.0 (one-time)"
        # Remove stale checksums in all local modules
        find . -name 'go.sum' -maxdepth 3 -print0 | xargs -0 -I{} sed -i \
          '/github.com\/LumeraProtocol\/lumera v1.8.0/d' {}
        # Clear module/build caches to avoid cached zips
        go clean -modcache || true
        rm -rf "$(go env GOCACHE)" || true

    - name: Set Go Private Modules
      shell: bash
      run: |
        go env -w GOPRIVATE=github.com/LumeraProtocol/lumera

    - name: Download Go dependencies
      shell: bash
      run: |
        go mod download
