name: Setup Environment
description: Sets up Go (dynamically from go.mod) and installs system dependencies

inputs: {}
outputs:
  go-version:
    description: "Go version parsed from go.mod"
    value: ${{ steps.get-go-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Get Go version from go.mod
      id: get-go-version
      shell: bash
      run: |
        GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+(\.[0-9]+)?$' go.mod | cut -d ' ' -f 2)
        echo "Found Go version: $GO_VERSION"
        echo "version=$GO_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.get-go-version.outputs.version }}
        cache: true

    - name: Install libwebp-dev
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebp-dev make 

    - name: Set Go Private Modules
      shell: bash
      run: |
        go env -w GOPRIVATE=github.com/LumeraProtocol/lumera

    - name: Download Go dependencies
      shell: bash
      run: |
        go mod download

    - name: Ensure modules are tidy
      shell: bash
      run: |
        set -euo pipefail
        modules=( "." "cmd/sncli" "sn-manager" "tests/system" )
        for m in "${modules[@]}"; do
          echo "::group::go mod tidy in $m"
          (cd "$m" && go mod tidy)
          echo "::endgroup::"
        done
        if ! git diff --quiet; then
          echo "The following files changed after go mod tidy:"
          git --no-pager diff --name-only
          echo "Please run 'go mod tidy' locally in the modules above and commit."
          exit 1
        fi
