// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=supernode_msg_mock.go -package=supernode_msg -source=interface.go
//

// Package supernode_msg is a generated GoMock package.
package supernode_msg

import (
	context "context"
	reflect "reflect"

	types "github.com/LumeraProtocol/lumera/x/supernode/v1/types"
	tx "github.com/cosmos/cosmos-sdk/types/tx"
	gomock "go.uber.org/mock/gomock"
)

// MockModule is a mock of Module interface.
type MockModule struct {
	ctrl     *gomock.Controller
	recorder *MockModuleMockRecorder
	isgomock struct{}
}

// MockModuleMockRecorder is the mock recorder for MockModule.
type MockModuleMockRecorder struct {
	mock *MockModule
}

// NewMockModule creates a new mock instance.
func NewMockModule(ctrl *gomock.Controller) *MockModule {
	mock := &MockModule{ctrl: ctrl}
	mock.recorder = &MockModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModule) EXPECT() *MockModuleMockRecorder {
	return m.recorder
}

// ReportMetrics mocks base method.
func (m *MockModule) ReportMetrics(ctx context.Context, identity string, metrics types.SupernodeMetrics) (*tx.BroadcastTxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportMetrics", ctx, identity, metrics)
	ret0, _ := ret[0].(*tx.BroadcastTxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportMetrics indicates an expected call of ReportMetrics.
func (mr *MockModuleMockRecorder) ReportMetrics(ctx, identity, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportMetrics", reflect.TypeOf((*MockModule)(nil).ReportMetrics), ctx, identity, metrics)
}
