# Supernode Configuration
supernode:
  key_name: "testkey1"
  identity: "lumera1em87kgrvgttrkvuamtetyaagjrhnu3vjy44at4"
  ip_address: "0.0.0.0"
  port: 4444

# Keyring Configuration
keyring:
  backend: "test"  # Options: test, file, os
  dir: "keys"      # Relative to base_dir
  password: "keyring-password"

# P2P Network Configuration
p2p:
  listen_address: "0.0.0.0"
  port: 4445
  data_dir: "data/p2p"  # Relative to base_dir
  bootstrap_nodes: ""
  external_ip: ""

# Lumera Chain Configuration
lumera:
  grpc_addr: "localhost:9090"
  chain_id: "lumera"
  timeout: 10

# RaptorQ Configuration
raptorq:
  service_address: "localhost:50051"
  files_dir: "raptorq_files"  # Relative to base_dir