# Supernode Configuration
supernode:
  key_name: "testkey3"
  identity: "lumera165s423s465qk57xzfs3w6gvlusuwe2fctwvs0q"
  ip_address: "0.0.0.0"
  port: 4448

# Keyring Configuration
keyring:
  backend: "test"
  dir: "keys"
  password: "keyring-password"

# P2P Network Configuration
p2p:
  listen_address: "0.0.0.0"
  port: 4449
  data_dir: "data/p2p"
  bootstrap_nodes: ""
  external_ip: ""

# Lumera Chain Configuration
lumera:
  grpc_addr: "localhost:9090"
  chain_id: "lumera"
  timeout: 10

# RaptorQ Configuration
raptorq:
  service_address: "localhost:50053"
  files_dir: "raptorq_files"